cacheFolder: .yarn/cache

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmMinimalAgeGate: "7d"

npmPreapprovedPackages:
  - "@infomaniak/*"

npmScopes:
  infomaniak:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.11.0.cjs
